### ISSUE TITLE
rename project

### ISSUE THREAD

**Issue by seanmiddleditch** [seanmiddleditch/formatxx#2]
Despite my attempts at due diligence, there is already a C++ string formatting library geared for standardization called formatxx, located at https://github.com/lichray/formatxx

So, this project being the newcomer, it needs a new name, out of respect if nothing else.

Unfortunately, I'm not all that creative with names, so I don't have any good ideas for a new name just yet.

**Comment by pmed** [comment]
Hi Sean!

Your attempt to create a lean formatting library, and especially using of array with function pointers to value formatting functions looks neat.

That other `formatxx` project is deprecated: lichray/formatxx@76dd59f, so this issue is not relevant.

Do you plan to continue work on the project? Sure, there is well known and quite mature https://github.com/fmtlib/fmt library, but as I remember, it has a burden of C++03 compatibility.

**Comment by seanmiddleditch** [comment]
I do plan to keep working on it. I'm using it in other projects. :)

fmt has gotten a lot better over time, which is good of course. It doesn't _quite_ meet my needs (exceptions, heavy, upstreams, etc.), but it may very well get there someday and obviate the need for formatxx.

**Comment by seanmiddleditch** [comment]
Probably not going to rename at this point, it's in the wild.
